CREATE DATABASE IF NOT EXISTS `testdb` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `testdb`

;

CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL,
   JOIN_DATE	  DATE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) VALUES (1, 'Paul', 32, 'California', 20000.00 ,'2001-07-13');
INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,JOIN_DATE) VALUES (2, 'Allen', 25, 'Texas', '2007-12-13');
INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) VALUES (3, 'Teddy', 23, 'Norway', 20000.00, DEFAULT );
INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) VALUES (4, 'Mark', 25, 'Rich-Mond ', 65000.00, '2007-12-13' ), (5, 'David', 27, 'Texas', 85000.00 , '2007-12-13');

-- CREATE TABLE `departments` (
-- 	`department_code` VARCHAR(50) NOT NULL,
-- 	`name` VARCHAR(200) NOT NULL,
-- 	`is_active` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
-- 	`created_at` DATETIME NOT NULL,
-- 	`updated_at` DATETIME NOT NULL,
-- 	PRIMARY KEY (`department_code`)
-- )
-- COLLATE='utf8_general_ci'
-- ENGINE=InnoDB
-- ;